/**
 * Writes docs/answer-keys.md: every question next to its answer key and worked solution, for the
 * human key review that gates release (SC3, SC15). Run with `pnpm keys:sheet`.
 */
import { writeFileSync } from 'node:fs';
import { formatDims, type Quantity } from '../src/checker/dims';
import { ALL_LESSONS, REVIEWED } from '../src/content/catalog';
import type { Step } from '../src/content/types';
import { lessonHash } from '../src/content/validate';

function showKey(answer: Quantity, angle: boolean): string {
  if (angle) return `${((answer.value[0] ?? 0) * 180 / Math.PI).toPrecision(5)}°`;
  const nums = answer.value.map((v) => Number(v.toPrecision(5)).toString());
  const value = nums.length === 1 ? (nums[0] ?? '') : `⟨${nums.join(', ')}⟩`;
  return `${value} ${formatDims(answer.dims)}`;
}

function stepLines(step: Step): string[] {
  switch (step.kind) {
    case 'explain': return [];
    case 'numeric': return [`- **${step.id}** (numeric${step.tol === undefined ? '' : `, tolerance ${step.tol * 100}%`}): ${step.prompt}`, `  - **Key:** ${showKey(step.answer, step.angle === true)}`, `  - Worked: ${step.worked}`];
    case 'triage': return [`- **${step.id}** (TRIAGE): ${step.problem}`, `  - **Key:** ${showKey(step.answer, false)}`, `  - Worked: ${step.worked}`, ...step.stages.filter((s) => s.check !== undefined).map((s) => `  - ${s.stage} check: ${s.check?.choices[s.check.answer] ?? ''}`)];
    case 'mcq': return [`- **${step.id}** (multiple choice): ${step.prompt}`, `  - **Key:** ${step.choices[step.answer] ?? '?'}`, `  - Why: ${step.explain}`];
    case 'predict': return [`- **${step.id}** (predict): ${step.prompt}`, `  - **Key:** ${step.choices[step.answer]?.text ?? '?'} (checked against a headless sim run in tests)`, `  - Reveal: ${step.reveal}`];
    case 'selfExplain': return [`- **${step.id}** (explain it simply): ${step.prompt}`, `  - Model answer: ${step.model}`];
  }
}

const lines: string[] = [
  '# Answer key sheet',
  '',
  'Generated by `pnpm keys:sheet`. Do not edit by hand.',
  '',
  'Review each lesson: read every question, check the key against your own working, and check the worked solution. When a lesson is right, run `pnpm keys:approve <lesson-id> "<your name>"`. Editing a lesson later changes its hash and takes it back out of release until it is reviewed again.',
  '',
];
for (const lesson of ALL_LESSONS) {
  const hash = lessonHash(lesson);
  const status = REVIEWED[lesson.id] === hash ? 'reviewed' : 'awaiting review';
  lines.push(`## ${lesson.chapter} · ${lesson.title}`, '', `\`${lesson.id}\` · hash \`${hash}\` · **${status}**`, '');
  for (const step of lesson.steps) lines.push(...stepLines(step));
  lines.push('');
}
writeFileSync('docs/answer-keys.md', lines.join('\n'));
console.log(`Wrote docs/answer-keys.md (${ALL_LESSONS.length} lessons)`);
